name = "HPL"
uuid = "9e52bb9f-844e-4299-848a-4df0e5a00971"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
